services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_HTTP_PORT=9411
    ports:
      - "5775:5775"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - jaeger-net
  jaeger-query:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-query
    ports:
      - "16686:16686" 
    depends_on:
      - jaeger
    networks:
      - jaeger-net
networks:
  jaeger-net:
    driver: bridge
